Repository openshift-kni/oran-hwmgr-plugin, pull requests merged in 2024-12, with the labels that each got.

#46 NO-ISSUE: Resync to latest o2ims code
  go.mod
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#47 NO-ISSUE: Drop github workflows
  .github/workflows/check-pull-request.yaml
  .github/workflows/requirements.txt
Labels: lgtm, approved, jira/valid-reference

#48 CNF-16110: Add dependabot.yml config
  .github/dependabot.yml
Labels: lgtm, approved, jira/valid-reference

#49 Update kube-rbac-proxy image reference
  bundle/manifests/oran-hwmgr-plugin.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: lgtm, approved

#50 Remove dev replace leftover from go.mod
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved

#56 set automatic deletion (NP ownerreference) for secrets and nodes
  adaptors/loopback/node.go
  adaptors/loopback/nodepool.go
  test/adaptors/loopback/adaptor_test.go
  test/adaptors/loopback/suite_test.go
Labels: lgtm, approved

#59 NO-ISSUE: Configure dependabot to ignore k8s.io major/minor updates for now
  .github/dependabot.yml
Labels: jira/valid-reference

#60 CNF-16104: Validate resources from hwmgr against nodepool request
  adaptors/dell-hwmgr/hwmgrclient/client.go
  adaptors/dell-hwmgr/nodepool.go
Labels: lgtm, approved, jira/valid-reference, tide/merge-method-squash

#63 fix annonations insertion (if nil map)
  adaptors/dell-hwmgr/nodepool.go
Labels: lgtm, approved

#62 Add support for provisioning updates via dell-hwmgr
  adaptors/dell-hwmgr/adaptor.go
  adaptors/dell-hwmgr/hwmgrclient/client.go
  adaptors/dell-hwmgr/node.go
  adaptors/dell-hwmgr/nodepool.go
  adaptors/loopback/adaptor.go
  adaptors/loopback/controller/hardwaremanager_controller.go
  adaptors/loopback/node.go
  adaptors/loopback/nodepool.go
  internal/controller/o2ims-hardwaremanagement/nodepool_controller.go
  internal/controller/utils/node_utils.go
  internal/controller/utils/utils.go
Labels: lgtm, approved

#65 Fix hwmgr job handling
  adaptors/dell-hwmgr/hwmgrclient/client.go
Labels: lgtm, approved

#67 Add node and nodepool CRDs to required list in CSV
  bundle/manifests/oran-hwmgr-plugin.clusterserviceversion.yaml
  config/manifests/bases/oran-hwmgr-plugin.clusterserviceversion.yaml
Labels: lgtm, approved
