Repository openshift-kni/oran-hwmgr-plugin, pull requests merged in 2025-04, with the labels that each got.

#153 CNF-17252: Add Inventory Subscription API paths
  Makefile
  internal/server/api/generated/inventory.generated.go
  internal/server/api/openapi.yaml
  internal/server/api/server.go
  pkg/inventory-client/generated/client.go
Labels: lgtm, approved, jira/valid-reference

#154 OCPBUGS-52680: CVE-2025-22869: Workaround for go 1.22
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/unix/auxv.go
  vendor/golang.org/x/sys/unix/auxv_unsupported.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/modules.txt
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#155 metal3: Update allocation MatchingLabels filter usage
  adaptors/metal3/bmh_manager.go
Labels: lgtm, approved

#156 Add resourceSelector support to metal3 adaptor
  adaptors/metal3/bmh_manager.go
  adaptors/metal3/inventory.go
  adaptors/metal3/node_allocator.go
  adaptors/metal3/nodepool.go
Labels: lgtm, approved

#157 CNF-17204: Add Day 2 BIOS configuration and firmware update support
  adaptors/metal3/adaptor.go
  adaptors/metal3/baremetalhost_manager.go
  adaptors/metal3/controller/hardwaremanager_controller.go
  adaptors/metal3/hostfirmwarecomponents_manager.go
  adaptors/metal3/hostfirmwaresettings_manager.go
  adaptors/metal3/hostupdatepolicy_manager.go
  adaptors/metal3/node_allocator.go
  adaptors/metal3/nodepool.go
  bundle/manifests/oran-hwmgr-plugin.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/utils/node_utils.go
Labels: lgtm, approved, jira/valid-reference

#163 CNF-17207 CNF-17208: Add error handling for detecting error status
  adaptors/metal3/baremetalhost_manager.go
  adaptors/metal3/hostfirmwarecomponents_manager.go
  adaptors/metal3/hostfirmwaresettings_manager.go
  adaptors/metal3/nodepool.go
Labels: lgtm, approved, jira/valid-reference

#164 metal3: Use non-caching client to get Node CR after patching it
  adaptors/adaptors.go
  adaptors/dell-hwmgr/adaptor.go
  adaptors/loopback/adaptor.go
  adaptors/metal3/adaptor.go
  adaptors/metal3/baremetalhost_manager.go
  cmd/main.go
  internal/controller/utils/node_utils.go
Labels: lgtm, approved

#166 CNF-17207 CNF-17208: Update nodepool status and handle reboot annotation
  adaptors/metal3/baremetalhost_manager.go
  adaptors/metal3/nodepool.go
Labels: lgtm, approved, jira/valid-reference

#167 metal3: Remove paused annotation prior to updating HFS/HFC CRs
  adaptors/metal3/baremetalhost_manager.go
  adaptors/metal3/nodepool.go
Labels: lgtm, approved
